# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_script:
    - sudo cp -r inst/fonts/roboto ~/.local/share/fonts

after_success:
    - Rscript -e 'covr::coveralls()'
